services:
  backend:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: notes_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    
volumes:
  postgres_data: